In [3]:
L1=[10,15,20,25]
print(L1)
type(L1)

[10, 15, 20, 25]


list

In [19]:
import numpy as np
a1 = np.array([1,2,3,4,5])
print(a1)
print(a1.dtype)

[1 2 3 4 5]
int64


In [20]:
a2 = np.array([1, 2, 3.3])
print(a2)
print(a2.dtype)

[1.  2.  3.3]
float64


In [15]:
a3 = np.array(['a','b','cat'])
print(a3)
print(a3.dtype)

['a' 'b' 'cat']
<U3


In [29]:
print(a1)
print(a1[0])
print(a1[1])
print(a1[0:3])
print(a1[1:4])


[1 2 3 4 5]
1
2
[1 2 3]
[2 3 4]


In [31]:
print(a1.shape)
print(a1.ndim)

(5,)
1


In [ ]:
### 2D

In [42]:
b= np.array([[1,2,3],[10,20,30]])
print(b)

[[ 1  2  3]
 [10 20 30]]


In [43]:
print(b.shape)
print(b.ndim)
print(b.dtype)

(2, 3)
2
int64


In [44]:
# access the values from array
print(b[0])
print(b[1])

[1 2 3]
[10 20 30]


In [50]:
b= np.array([[1,2,3],[10,20,30],[100,200,300]])
print(b)
print("************")
print(b[0:2, : ])
print("************")
print(b[ : , 0:2 ])
print("************")
print(b[0:2 , 0:2 ])


[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]
************
[[ 1  2  3]
 [10 20 30]]
************
[[  1   2]
 [ 10  20]
 [100 200]]
************
[[ 1  2]
 [10 20]]


In [60]:
b2 = np.array([[1,2,3],[4,5,51.5],[6,8,50.5]])
print(b2)
# print 1st row, 2nd col
print(b2[0,1])
# print 2nd and 3rd row
print(b2[1: , :])
# print 3rd col only
print(b2[: ,2])
# print 2row,3rd col
print(b2[1,2])
# print 3rd row
print(b[2,:])

[[ 1.   2.   3. ]
 [ 4.   5.  51.5]
 [ 6.   8.  50.5]]
2.0
[[ 4.   5.  51.5]
 [ 6.   8.  50.5]]
[ 3.  51.5 50.5]
51.5
[100 200 300]


In [61]:
b3 = np.array([True,False,True,False])
print(b3)
print(b3.dtype)


[ True False  True False]
bool


In [63]:
print(b3.astype('int'))

[1 0 1 0]


In [65]:
b4 = np.array([10,20,30,0])
print(b4.dtype)
print(b4.astype('bool'))

int64
[ True  True  True False]


In [70]:
np.array([1,2,3],[1,2])

TypeError: ignored

In [72]:
a1 = np.array([1,2,3])
a2 = np.array([2,3,4])
print(a1+a2)
print(a1-a2)
print(a1*a2)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]


In [76]:
a1 = np.array([[1,2,3],[3,4,5]])
a2 = np.array([[2,3,4],[4,5,6]])
print(a1)
print(a2)
print("*******")
print(a1+a2)
print("*******")
print(a1-a2)
print("*******")
print(a1*a2)

[[1 2 3]
 [3 4 5]]
[[2 3 4]
 [4 5 6]]
*******
[[ 3  5  7]
 [ 7  9 11]]
*******
[[-1 -1 -1]
 [-1 -1 -1]]
*******
[[ 2  6 12]
 [12 20 30]]


In [81]:
print(np.multiply(a1,a2))
print(np.dot(a1,np.transpose(a2)))

[[ 2  6 12]
 [12 20 30]]
[[20 32]
 [38 62]]


In [92]:
# generate random integers --- with size
a1 = np.random.randint(20,size=10)
a1

array([11, 12, 17,  3,  0,  9,  5,  8, 14, 19])

In [93]:
a2 = np.random.randint(50,size=20)
a2

array([40, 13, 27, 33, 25, 47,  3, 10, 21, 43, 49, 30,  6, 23,  0, 47, 33,
       14, 17,  8])

In [86]:
np.array(a1,ndmin=2)

array([[16,  5,  5, 11,  6,  0, 19,  0, 12, 17]])

In [94]:
a3 = np.random.randint(20,size=(2,3))
print(a3)
#?np.random.randint

[[ 9 13  5]
 [18  0  0]]


In [95]:
a4 = np.random.randint(20,size=(2,3))
print(a4)

[[19  3 18]
 [10  0 11]]


In [100]:
print(a1)
print(a2)
print("**************")
print(np.concatenate([a1,a2]))

[11 12 17  3  0  9  5  8 14 19]
[40 13 27 33 25 47  3 10 21 43 49 30  6 23  0 47 33 14 17  8]
**************
[11 12 17  3  0  9  5  8 14 19 40 13 27 33 25 47  3 10 21 43 49 30  6 23
  0 47 33 14 17  8]


In [101]:
print(a3)
print(a4)
print("*********")
print(np.concatenate([a3,a4]))

[[ 9 13  5]
 [18  0  0]]
[[19  3 18]
 [10  0 11]]
*********
[[ 9 13  5]
 [18  0  0]
 [19  3 18]
 [10  0 11]]


In [103]:
print(a3)
print(a4)
print("*********")
print(np.concatenate([a3,a4],axis=1))

[[ 9 13  5]
 [18  0  0]]
[[19  3 18]
 [10  0 11]]
*********
[[ 9 13  5 19  3 18]
 [18  0  0 10  0 11]]


In [104]:
a5 = np.random.randint(50,size=(2,3))
a6 = np.random.randint(50,size=(3,2))
print(a5)
print(a6)


[[ 0 29 38]
 [16 42 18]]
[[27 12]
 [ 6 37]
 [39 38]]


In [105]:
print("*********")
print(np.concatenate([a5,a6],axis=1))

*********


ValueError: ignored

In [110]:
a7 = np.arange(0,40,5)
print(a7)

[ 0  5 10 15 20 25 30 35]


In [112]:
a8 = np.arange(40,80,5)
print(a8)

[40 45 50 55 60 65 70 75]


In [118]:
print(np.stack([a7,a8]))

[[ 0  5 10 15 20 25 30 35]
 [40 45 50 55 60 65 70 75]]


In [117]:
np.concatenate([a7,a8],axis=0)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [120]:
a9 = np.arange(0,100,10)
print(a9)

[ 0 10 20 30 40 50 60 70 80 90]


In [122]:
np.reshape(a9,(2,5))

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [123]:
np.reshape(a9,(5,2))

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

In [124]:
np.reshape(a9,(1,10))

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [125]:
np.reshape(a9,(10,1))

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])